ALTER TABLE `User` MODIFY `role` ENUM('SUPER_ADMIN', 'ASSOCIATION_ADMIN', 'SCHOOL_ADMIN', 'CANTEEN_OPERATOR', 'CANTEEN_CASHIER', 'CANTEEN_OWNER', 'AUDITOR') NOT NULL;

UPDATE `User`
SET `role` = 'CANTEEN_CASHIER'
WHERE `role` = 'CANTEEN_OPERATOR' AND `schoolId` IS NOT NULL;

UPDATE `User`
SET `role` = 'CANTEEN_OWNER'
WHERE `role` = 'CANTEEN_OPERATOR' AND `schoolId` IS NULL;
